# Generated by Django 2.0.3 on 2018-03-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelperson',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
