# Generated by Django 2.0.3 on 2018-03-10 02:04

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_modelperson_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelperson',
            options={'ordering': ('-pk',), 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-pk',), 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=s3direct.fields.S3DirectField(default='--empty :( '),
            preserve_default=False,
        ),
    ]
