# Generated by Django 2.0.3 on 2018-03-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180325_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelperson',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
